### ISSUE TITLE
App Crashes in Retail Mode XBOX ONE (S)

### ISSUE THREAD

**Issue by xvenomx00** [Nun-z/DURANGO-FTP#1]
Hey! So I figured give this app a try. Before the revision addon (runFullTrust) I was able to load it up on the retail side of Xbox perfect but after I seen you updated it I added it to retail side again and gave it a try and it opens to black screen then it closes and goes back to home screen.

> https://github.com/Nun-z/DURANGO-FTP/blob/main/UniversalFtpServer/Package.appxmanifest

**Comment by Nun-z** [comment]
Sorry about that.  I'm still experimenting with it.  I'll remove the runFullTrust capability, as it does seem to be problematic.

**Comment by xvenomx00** [comment]
Oh No Problem!! I still have the original one still installed I installed this one as a different name to test it out thought I'd give you a heads-up, I'll start looking into the SU elevation tmrw and see what I can whip up!

**Comment by Nun-z** [comment]
Awesome, thanks.
